import { useQuery } from '@tanstack/react-query';

import { kataToHira } from '../../../../main/features/core/lyrics/furigana';

// JMdict (EDRDG, CC BY-SA 4.0) compact JSON, generated by
// scripts/gen-jmdict.py following the KANJIDIC2 pipeline pattern.
export type WordEntry = {
    kanji: null | string;
    reading: string;
    senses: WordSense[];
};

export type WordLookupInput = {
    /** Dictionary (base) form from the kuromoji token, null when the analyzer has none */
    basicForm: null | string;
    /** Kuromoji top-level part-of-speech (Japanese), used to rank homographs */
    pos: null | string;
    /** Full-token reading in hiragana */
    reading: null | string;
    surface: string;
};

export type WordSense = {
    glosses: string[];
    pos: string[];
};

type CompactEntry = [string, string, CompactSense[]];

type CompactSense = [string, string[]];

type WordDictionary = {
    entries: CompactEntry[];
    index: Record<string, number[]>;
};

let dictionaryPromise: null | Promise<WordDictionary> = null;

const loadDictionary = (): Promise<WordDictionary> => {
    dictionaryPromise ??= import('../assets/jmdict-compact.json').then(
        (module) => module.default as unknown as WordDictionary,
    );

    return dictionaryPromise;
};

const hiraToKata = (text: string): string =>
    text.replace(/[ぁ-ゖ]/g, (char) => String.fromCharCode(char.charCodeAt(0) + 0x60));

/**
 * Ordered lookup keys for a token: dictionary form first (conjugated verbs and
 * adjectives resolve to their JMdict headword), then the surface form, then
 * kana-normalized variants of both, then the token reading. The index holds
 * both kanji and reading forms, so kana-written words and katakana loanwords
 * resolve without a kanji headword.
 */
export const buildLookupCandidates = (input: WordLookupInput): string[] => {
    const raw = [input.basicForm, input.surface];
    const kanaVariants = raw
        .filter((form): form is string => !!form)
        .flatMap((form) => [kataToHira(form), hiraToKata(form)]);
    const readingVariants = input.reading ? [input.reading, hiraToKata(input.reading)] : [];

    const candidates = [...raw, ...kanaVariants, ...readingVariants];

    return [...new Set(candidates.filter((form): form is string => !!form))];
};

/** Does a JMdict sense POS code belong to the kuromoji part-of-speech family? */
const matchesKuromojiPos = (code: string, kuromojiPos: string): boolean => {
    switch (kuromojiPos) {
        case '副詞':
            return code.startsWith('adv');
        case '助動詞':
            return code.startsWith('aux') || code === 'cop';
        case '助詞':
            return code === 'prt';
        case '動詞':
            return code.startsWith('v');
        case '名詞':
            return code.startsWith('n') || code === 'pn' || code === 'num' || code === 'ctr';
        case '形容詞':
            return code.startsWith('adj-i');
        case '感動詞':
            return code === 'int';
        case '接続詞':
            return code === 'conj';
        case '接頭詞':
            return code === 'pref';
        case '連体詞':
            return code === 'adj-pn';
        default:
            return false;
    }
};

const toWordEntry = (entry: CompactEntry): WordEntry => ({
    kanji: entry[0] || null,
    reading: entry[1],
    senses: entry[2].map((sense) => ({
        glosses: sense[1],
        pos: sense[0] ? sense[0].split(';') : [],
    })),
});

const entryMatchesPos = (entry: WordEntry, kuromojiPos: null | string): boolean =>
    !!kuromojiPos &&
    entry.senses.some((sense) => sense.pos.some((code) => matchesKuromojiPos(code, kuromojiPos)));

/**
 * The first candidate key with index hits wins (a dictionary-form hit must not
 * be diluted by surface-form homographs). Entries whose senses match the
 * token's part-of-speech rank first, so e.g. the particle は outranks the
 * noun 歯 for a 助詞 token.
 */
export const lookupWordEntries = (
    dictionary: WordDictionary,
    candidates: string[],
    kuromojiPos: null | string,
): WordEntry[] => {
    for (const candidate of candidates) {
        const hits = dictionary.index[candidate];
        if (!hits?.length) {
            continue;
        }

        const entries = hits.map((idx) => toWordEntry(dictionary.entries[idx]));

        return [
            ...entries.filter((entry) => entryMatchesPos(entry, kuromojiPos)),
            ...entries.filter((entry) => !entryMatchesPos(entry, kuromojiPos)),
        ];
    }

    return [];
};

/** Lazily loads the bundled JMdict dictionary and returns the entries for a lyrics token */
export const useWordInfo = (input: null | WordLookupInput) => {
    return useQuery({
        enabled: input !== null,
        queryFn: async (): Promise<WordEntry[]> => {
            if (!input) {
                return [];
            }

            const dictionary = await loadDictionary();

            return lookupWordEntries(dictionary, buildLookupCandidates(input), input.pos);
        },
        queryKey: ['jmdict', input],
        staleTime: Infinity,
    });
};
